const LANG_STORAGE_KEY = "chess_analytics_lang";
const SUPPORTED_LANGS = ["en", "fr", "zh", "es", "sv"];
const LANG_LABELS = {
  en: "English",
  fr: "Français",
  zh: "中文",
  es: "Español",
  sv: "Svenska"
};

const TRANSLATIONS = {
  en: {
    lang_selector_label: "Language",
    nav_account: "Account",
    nav_support: "Support",
    nav_logout: "Log Out",
    nav_back_home: "Back to Home",
    nav_back_login: "Back to Login",
    login_title: "User Login",
    login_hint: "Sign in to use the analytics dashboard.",
    login_username: "Username",
    login_password: "Password",
    login_button: "Log In",
    login_guest: "Login as Guest",
    login_create_account: "Create Account",
    login_forgot_password: "Forgot Password?",
    register_title: "Create Account",
    register_hint: "Register a new account to use Chess Data Stats.",
    register_username: "Username",
    register_email: "Email",
    register_password: "Password (min 12, upper/lower/number/symbol)",
    register_button: "Create Account",
    forgot_title: "Forgot Password",
    forgot_hint: "Request a reset email, then set a new password.",
    forgot_username: "Username",
    forgot_request_button: "Request Reset Email",
    forgot_token: "Reset Token",
    forgot_new_password: "New Password (min 12, upper/lower/number/symbol)",
    forgot_reset_button: "Reset Password",
    account_title: "Account",
    account_hint: "Set or update your email for password reset.",
    account_email: "Email",
    account_save: "Save Email",
    support_title: "Support",
    support_hint: "Leave a message (max 200 characters) and we will receive it by email.",
    support_message_label: "Message",
    support_message_placeholder: "Type your message...",
    support_send_button: "Send Message",
    support_guest_label: "Not signed in (guest)",
    home_title: "Chess Data Stats",
    home_hint: "Add one or more usernames and choose a date range (max 120 days).",
    home_platform: "Platform",
    home_range: "Range (days)",
    home_default_mode: "Default mode",
    home_optional_exact_range: "Optional: exact date range",
    home_from: "From",
    home_to: "To",
    home_date_override_hint: "If both dates are set, they override Range.",
    home_game_types: "Game Types",
    home_bullet: "Bullet",
    home_blitz: "Blitz",
    home_rapid: "Rapid",
    home_add: "Add",
    home_upload_csv: "Upload CSV",
    home_csv_hint: "CSV: one username per line or comma-separated.",
    home_generate: "Generate Stats Page",
    home_entry_fetch_title: "Fetch Game Data",
    home_entry_fetch_desc: "Pull online games and build player stats tables.",
    home_entry_analysis_title: "Game Analysis",
    home_entry_analysis_desc: "Paste or upload PGN and run Stockfish analysis.",
    home_banner_fetch_title: "Fetch Online Game Stats",
    home_banner_fetch_hint: "Pull games from Chess.com or Lichess and generate player stats.",
    home_banner_pgn_title: "Upload PGN + Stockfish Analysis",
    home_banner_pgn_hint: "Upload a PGN file and run engine analysis for move-by-move scoring.",
    home_pgn_file_label: "PGN File",
    home_pgn_input_mode_label: "Input Mode",
    home_pgn_input_mode_upload: "Upload File",
    home_pgn_input_mode_paste: "Paste PGN",
    home_pgn_paste_label: "Paste PGN",
    home_pgn_paste_placeholder: "Paste PGN text here...",
    home_pgn_depth_label: "Analysis Depth",
    home_pgn_upload_btn: "Load PGN",
    home_pgn_analyze_btn: "Run Stockfish Analysis",
    home_pgn_download_btn: "Download CSV",
    home_pgn_auto_load_hint: "PGN loads automatically from file or pasted text.",
    home_pgn_ready_from_file: "PGN file loaded ({chars} chars).",
    home_pgn_ready_from_paste: "Pasted PGN ready ({chars} chars).",
    home_pgn_ready_from_both: "File and pasted PGN match ({chars} chars).",
    home_pgn_conflict: "PGN conflict: uploaded file and pasted text are different. Keep only one source or make them match.",
    home_pgn_no_input: "Please upload a PGN file or paste PGN text first.",
    home_pgn_invalid_format: "Invalid PGN format. Please re-fill PGN and try again.",
    home_pgn_loaded: "PGN loaded ({chars} chars).",
    home_pgn_load_failed: "Failed to load PGN: {error}",
    home_pgn_analyzing: "Analyzing with Stockfish...",
    home_pgn_analysis_done: "Analysis complete: {count} moves, {failed} failed evals.",
    home_pgn_analyze_failed: "Failed to analyze PGN.",
    home_pgn_too_large: "PGN is too large.",
    home_pgn_rate_limited: "Too many requests. Please try again shortly.",
    pgn_eval_move_number: "Move #",
    pgn_eval_side: "Side",
    pgn_eval_move: "Move",
    pgn_eval_score: "Eval Score",
    pgn_eval_bestmove: "Best Move",
    pgn_eval_bestmove_eval: "Best Move Eval",
    pgn_eval_eval_gap: "Eval Gap",
    pgn_eval_accuracy: "Accuracy",
    pgn_eval_is_book_move: "Book Move",
    pgn_eval_opening_eco: "Opening ECO",
    pgn_eval_opening_name: "Opening Name",
    pgn_eval_white_clock: "White Clock",
    pgn_eval_black_clock: "Black Clock",
    pgn_eval_wdl: "WDL",
    pgn_analysis_title: "Stockfish PGN Analysis",
    pgn_analysis_hint: "We analyze your PGN move-by-move and show evaluation scores.",
    pgn_analysis_starting: "Preparing analysis...",
    pgn_analysis_back_home: "Back to Home",
    pgn_analysis_download_csv: "Download CSV",
    pgn_analysis_progress_title: "Analyzing PGN",
    pgn_analysis_progress_running: "Running Stockfish analysis...",
    pgn_analysis_slow_hint: "taking longer than expected, still running",
    pgn_analysis_progress_done: "Analysis completed.",
    pgn_analysis_progress_missing: "No PGN input found.",
    pgn_analysis_eta: "Estimated time remaining: --",
    pgn_analysis_eta_seconds: "Estimated time remaining: {seconds}s",
    pgn_analysis_eta_done: "Completed.",
    pgn_analysis_cancel: "Cancel",
    pgn_analysis_cancelled: "Analysis cancelled.",
    pgn_analysis_close: "Close",
    pgn_analysis_missing_input: "No PGN input found. Please go back and upload file or paste PGN.",
    stats_title: "Game Stats",
    stats_loading: "Loading data...",
    stats_username: "Username",
    stats_games: "Games",
    stats_breakdown: "Breakdown",
    stats_win_rate: "Win Rate",
    stats_avg_duration: "Avg Game Duration",
    stats_rating_change: "Rating Change (Range)",
    stats_last_played: "Last Played",
    stats_download_csv: "Download CSV",
    stats_download_raw: "Download Raw Data",
    stats_view_raw: "View Raw Data",
    stats_raw_preview: "Raw Data Preview",
    stats_raw_preview_hint: "Preview raw games first, then choose whether to download.",
    stats_raw_platform: "Platform",
    stats_raw_white_player: "White Player",
    stats_raw_white_rating: "White Rating",
    stats_raw_black_player: "Black Player",
    stats_raw_black_rating: "Black Rating",
    stats_raw_rating_gap: "Rating Gap (White-Black)",
    stats_raw_game_type: "Game Type",
    stats_raw_result: "Result",
    stats_raw_game_link: "Game Link",
    stats_raw_played_at: "Played At (UTC)",
    stats_raw_duration_ms: "Duration Ms",
    stats_raw_duration_min: "Duration (min)",
    stats_raw_rating_diff: "Rating Diff (User Change)",
    stats_raw_rating: "Rating",
    raw_prev_page: "Previous",
    raw_next_page: "Next",
    nav_back_stats: "Back to Game Stats",
    auth_signed_in_as: "Signed in as {username}",
    msg_logging_in: "Logging in...",
    msg_login_failed: "Login failed. Check username/password.",
    msg_account_locked_wait: "This account is temporarily locked. Try again in {wait}s.",
    msg_account_locked_later: "This account is temporarily locked. Please try again later.",
    msg_rate_limited_wait: "Too many attempts. Try again in {wait}s.",
    msg_rate_limited_later: "Too many attempts. Please try again later.",
    msg_payload_too_large: "Request too large. Please shorten input and retry.",
    msg_logging_guest: "Logging in as guest...",
    msg_guest_login_failed: "Guest login failed: {status}{detail}",
    msg_creating_account: "Creating account...",
    msg_username_exists: "This username already exists.",
    msg_email_exists: "This email is already registered.",
    msg_email_required: "Email is required.",
    msg_invalid_email: "Please enter a valid email address.",
    msg_invalid_username: "Username must be 3-32 chars: letters, numbers, _ or -.",
    msg_register_failed: "Register failed.",
    msg_account_created_redirect: "Account created. Redirecting to login...",
    msg_requesting_reset_email: "Requesting reset email...",
    msg_request_reset_failed: "Failed to request reset email.",
    msg_reset_service_not_configured: "Reset email service is not configured yet. Please contact support.",
    msg_reset_token_ready: "Reset token ready: {token}. Now set a new password below.",
    msg_reset_email_sent_if_exists: "If the account exists, reset instructions have been sent to email.",
    msg_resetting_password: "Resetting password...",
    msg_reset_token_invalid: "Reset token is invalid or expired.",
    msg_password_reset_failed: "Password reset failed.",
    msg_password_reset_success_redirect: "Password reset successful. Redirecting to login...",
    msg_saving_email: "Saving email...",
    msg_email_in_use: "This email is already used by another account.",
    msg_save_email_failed: "Failed to save email ({error}).",
    msg_email_saved: "Email saved: {email}",
    msg_password_too_short: "Password must be at least 12 characters.",
    msg_password_too_weak: "Password is too common. Choose a stronger one.",
    msg_password_missing_uppercase: "Password must include at least one uppercase letter.",
    msg_password_missing_lowercase: "Password must include at least one lowercase letter.",
    msg_password_missing_number: "Password must include at least one number.",
    msg_password_missing_symbol: "Password must include at least one symbol.",
    support_sending: "Sending message...",
    support_send_success: "Message sent. Thank you for your feedback.",
    support_send_failed: "Failed to send message. Please try again.",
    support_message_required: "Message is required.",
    support_message_too_long: "Message must be at most {max} characters.",
    support_email_service_not_configured: "Support email service is not configured yet.",
    faq_page_title: "FAQ | Chess Data Stats",
    faq_heading: "FAQ",
    faq_hint: "Common questions about data fetch and PGN analysis.",
    faq_q1: "How many days can I fetch game data?",
    faq_a1: "The selected date range cannot exceed 120 days.",
    faq_q2: "Can I upload PGN by file and by paste?",
    faq_a2: "Yes. You can upload a PGN file or paste PGN text. If they conflict, keep one source.",
    faq_q3: "Can I export analysis results to CSV?",
    faq_a3: "Yes. Both game stats and PGN analysis outputs can be downloaded as CSV.",
    faq_q4: "Which platforms are supported?",
    faq_a4: "Game data fetching supports Chess.com and Lichess.",
    faq_q5: "How are eval score and best move obtained in PGN analysis?",
    faq_a5: "Eval score comes from engine evaluation after the played move. Best move and best move eval are engine recommendations from the position before that move.",
    faq_q6: "What is Stockfish?",
    faq_a6: "Stockfish is a strong open-source chess engine used to evaluate positions and suggest best moves.",
    app_remove: "Remove",
    app_more_usernames: "+{count} more usernames",
    alert_invalid_username_format: "Invalid username format: 2-30 characters, letters/numbers/_/- only.",
    alert_no_usernames_csv: "No usernames found in CSV.",
    alert_csv_imported: "CSV imported: {added} added, {invalid} invalid.",
    alert_csv_read_failed: "Failed to read CSV: {error}",
    alert_add_user_first: "Please add at least one username first.",
    alert_select_game_type: "Please select at least one game type (Bullet/Blitz/Rapid).",
    alert_select_both_dates_or_empty: "Please select both From and To dates, or leave both empty.",
    alert_invalid_date_selection: "Invalid date selection.",
    alert_from_after_to: "From date cannot be after To date.",
    alert_max_120_days: "Range cannot exceed 120 days. You entered {days} days.",
    stats_no_usernames: "No usernames received. Please go back to the home page and add accounts.",
    stats_users_loading: "{count} users total on {platform} ({types}), loading...",
    stats_completed_progress: "Completed {finished}/{total} ({platform}, {types})",
    stats_completed_range: "Completed {finished}/{total}. Range: {range} ({platform}, {types}).",
    stats_load_failed: "Load failed: {error}",
    stats_unknown_error: "Unknown error",
    stats_result_win: "Win",
    stats_result_loss: "Loss",
    stats_result_draw: "Draw",
    stats_result_unknown: "Unknown"
  },
  fr: {
    lang_selector_label: "Langue",
    nav_account: "Compte",
    nav_support: "Support",
    nav_logout: "Se déconnecter",
    nav_back_home: "Retour à l'accueil",
    nav_back_login: "Retour à la connexion",
    login_title: "Connexion utilisateur",
    login_hint: "Connectez-vous pour utiliser le tableau de bord.",
    login_username: "Nom d'utilisateur",
    login_password: "Mot de passe",
    login_button: "Se connecter",
    login_guest: "Connexion invité",
    login_create_account: "Créer un compte",
    login_forgot_password: "Mot de passe oublié ?",
    register_title: "Créer un compte",
    register_hint: "Créez un compte pour utiliser Chess Data Stats.",
    register_username: "Nom d'utilisateur",
    register_email: "E-mail",
    register_password: "Mot de passe (min 12, maj/min/chiffre/symbole)",
    register_button: "Créer un compte",
    forgot_title: "Mot de passe oublié",
    forgot_hint: "Demandez un e-mail de réinitialisation puis définissez un nouveau mot de passe.",
    forgot_username: "Nom d'utilisateur",
    forgot_request_button: "Demander l'e-mail",
    forgot_token: "Jeton de réinitialisation",
    forgot_new_password: "Nouveau mot de passe (min 12, maj/min/chiffre/symbole)",
    forgot_reset_button: "Réinitialiser le mot de passe",
    account_title: "Compte",
    account_hint: "Définissez ou mettez à jour votre e-mail pour la réinitialisation.",
    account_email: "E-mail",
    account_save: "Enregistrer l'e-mail",
    support_title: "Support",
    support_hint: "Laissez un message (max 200 caractères), il sera envoyé par e-mail.",
    support_message_label: "Message",
    support_message_placeholder: "Écrivez votre message...",
    support_send_button: "Envoyer le message",
    support_guest_label: "Non connecté (invité)",
    home_title: "Chess Data Stats",
    home_hint: "Ajoutez des utilisateurs et choisissez une plage de dates (max 120 jours).",
    home_platform: "Plateforme",
    home_range: "Plage (jours)",
    home_default_mode: "Mode par défaut",
    home_optional_exact_range: "Optionnel : plage exacte",
    home_from: "De",
    home_to: "À",
    home_date_override_hint: "Si les deux dates sont définies, elles remplacent la plage.",
    home_game_types: "Types de parties",
    home_bullet: "Bullet",
    home_blitz: "Blitz",
    home_rapid: "Rapide",
    home_add: "Ajouter",
    home_upload_csv: "Importer CSV",
    home_csv_hint: "CSV : un nom d'utilisateur par ligne ou séparé par des virgules.",
    home_generate: "Générer la page de stats",
    home_entry_fetch_title: "Récupérer les parties",
    home_entry_fetch_desc: "Récupérez les parties en ligne et construisez des tableaux de statistiques.",
    home_entry_analysis_title: "Analyse de partie",
    home_entry_analysis_desc: "Collez ou importez un PGN et lancez l'analyse Stockfish.",
    home_banner_fetch_title: "Récupérer les statistiques en ligne",
    home_banner_fetch_hint: "Récupérez les parties depuis Chess.com ou Lichess et générez les statistiques.",
    home_banner_pgn_title: "Importer PGN + analyse Stockfish",
    home_banner_pgn_hint: "Importez un fichier PGN et lancez une analyse coup par coup.",
    home_pgn_file_label: "Fichier PGN",
    home_pgn_input_mode_label: "Mode d'entrée",
    home_pgn_input_mode_upload: "Importer un fichier",
    home_pgn_input_mode_paste: "Coller PGN",
    home_pgn_paste_label: "Coller PGN",
    home_pgn_paste_placeholder: "Collez le texte PGN ici...",
    home_pgn_depth_label: "Profondeur d'analyse",
    home_pgn_upload_btn: "Charger PGN",
    home_pgn_analyze_btn: "Lancer l'analyse Stockfish",
    home_pgn_download_btn: "Télécharger CSV",
    home_pgn_auto_load_hint: "Le PGN est chargé automatiquement depuis le fichier ou le texte collé.",
    home_pgn_ready_from_file: "Fichier PGN prêt ({chars} caractères).",
    home_pgn_ready_from_paste: "PGN collé prêt ({chars} caractères).",
    home_pgn_ready_from_both: "Le fichier et le texte collé correspondent ({chars} caractères).",
    home_pgn_conflict: "Conflit PGN : le fichier et le texte collé sont différents. Gardez une seule source ou faites-les correspondre.",
    home_pgn_no_input: "Importez un fichier PGN ou collez du texte PGN.",
    home_pgn_invalid_format: "Format PGN invalide. Veuillez ressaisir le PGN puis réessayer.",
    home_pgn_loaded: "PGN chargé ({chars} caractères).",
    home_pgn_load_failed: "Échec du chargement PGN : {error}",
    home_pgn_analyzing: "Analyse Stockfish en cours...",
    home_pgn_analysis_done: "Analyse terminée : {count} coups, {failed} évaluations en échec.",
    home_pgn_analyze_failed: "Échec de l'analyse PGN.",
    home_pgn_too_large: "Le PGN est trop volumineux.",
    home_pgn_rate_limited: "Trop de requêtes. Réessayez bientôt.",
    pgn_eval_move_number: "N° coup",
    pgn_eval_side: "Camp",
    pgn_eval_move: "Coup",
    pgn_eval_score: "Évaluation",
    pgn_eval_bestmove: "Meilleur coup",
    pgn_eval_bestmove_eval: "Éval meilleur coup",
    pgn_eval_eval_gap: "Écart d'éval",
    pgn_eval_accuracy: "Précision",
    pgn_eval_is_book_move: "Coup théorique",
    pgn_eval_opening_eco: "ECO ouverture",
    pgn_eval_opening_name: "Nom de l'ouverture",
    pgn_eval_white_clock: "Temps blanc",
    pgn_eval_black_clock: "Temps noir",
    pgn_eval_wdl: "G/N/P",
    pgn_analysis_title: "Analyse PGN Stockfish",
    pgn_analysis_hint: "Nous analysons votre PGN coup par coup et affichons l'évaluation.",
    pgn_analysis_starting: "Préparation de l'analyse...",
    pgn_analysis_back_home: "Retour à l'accueil",
    pgn_analysis_download_csv: "Télécharger CSV",
    pgn_analysis_progress_title: "Analyse du PGN",
    pgn_analysis_progress_running: "Analyse Stockfish en cours...",
    pgn_analysis_slow_hint: "plus long que prévu, toujours en cours",
    pgn_analysis_progress_done: "Analyse terminée.",
    pgn_analysis_progress_missing: "Aucune entrée PGN trouvée.",
    pgn_analysis_eta: "Temps restant estimé : --",
    pgn_analysis_eta_seconds: "Temps restant estimé : {seconds}s",
    pgn_analysis_eta_done: "Terminé.",
    pgn_analysis_cancel: "Annuler",
    pgn_analysis_cancelled: "Analyse annulée.",
    pgn_analysis_close: "Fermer",
    pgn_analysis_missing_input: "Aucune entrée PGN trouvée. Revenez en arrière et ajoutez un PGN.",
    stats_title: "Statistiques des parties",
    stats_loading: "Chargement des données...",
    stats_username: "Nom d'utilisateur",
    stats_games: "Parties",
    stats_breakdown: "Répartition",
    stats_win_rate: "Taux de victoire",
    stats_avg_duration: "Durée moyenne",
    stats_rating_change: "Variation Elo (période)",
    stats_last_played: "Dernière partie",
    stats_download_csv: "Télécharger CSV",
    stats_download_raw: "Télécharger les données brutes",
    stats_view_raw: "Voir les données brutes",
    stats_raw_preview: "Aperçu des données brutes",
    stats_raw_preview_hint: "Prévisualisez d'abord les parties brutes, puis choisissez de télécharger.",
    stats_raw_platform: "Plateforme",
    stats_raw_white_player: "Joueur blanc",
    stats_raw_white_rating: "Classement blanc",
    stats_raw_black_player: "Joueur noir",
    stats_raw_black_rating: "Classement noir",
    stats_raw_rating_gap: "Écart de classement (Blanc-Noir)",
    stats_raw_game_type: "Type de partie",
    stats_raw_result: "Résultat",
    stats_raw_game_link: "Lien de partie",
    stats_raw_played_at: "Joué le (UTC)",
    stats_raw_duration_ms: "Durée ms",
    stats_raw_duration_min: "Durée (min)",
    stats_raw_rating_diff: "Diff. Elo (variation utilisateur)",
    stats_raw_rating: "Elo",
    raw_prev_page: "Précédent",
    raw_next_page: "Suivant",
    nav_back_stats: "Retour aux statistiques",
    support_sending: "Envoi du message...",
    support_send_success: "Message envoyé. Merci pour votre retour.",
    support_send_failed: "Envoi échoué. Veuillez réessayer.",
    support_message_required: "Le message est requis.",
    support_message_too_long: "Le message doit contenir au maximum {max} caractères.",
    support_email_service_not_configured: "Le service e-mail de support n'est pas encore configuré.",
    faq_page_title: "FAQ | Chess Data Stats",
    faq_heading: "FAQ",
    faq_hint: "Questions fréquentes sur la récupération de données et l'analyse PGN.",
    faq_q1: "Combien de jours de parties puis-je récupérer ?",
    faq_a1: "La plage sélectionnée ne peut pas dépasser 120 jours.",
    faq_q2: "Puis-je importer un PGN par fichier et par collage ?",
    faq_a2: "Oui. Vous pouvez importer un fichier PGN ou coller un texte PGN. En cas de conflit, gardez une seule source.",
    faq_q3: "Puis-je exporter les résultats d'analyse en CSV ?",
    faq_a3: "Oui. Les statistiques et les résultats d'analyse PGN peuvent être téléchargés en CSV.",
    faq_q4: "Quelles plateformes sont prises en charge ?",
    faq_a4: "La récupération des parties prend en charge Chess.com et Lichess.",
    faq_q5: "Comment la note d'évaluation et le meilleur coup sont-ils obtenus dans l'analyse PGN ?",
    faq_a5: "La note d'évaluation provient de l'évaluation moteur après le coup joué. Le meilleur coup et son évaluation proviennent de la recommandation moteur avant ce coup.",
    faq_q6: "Qu'est-ce que Stockfish ?",
    faq_a6: "Stockfish est un moteur d'échecs open source très puissant, utilisé pour évaluer les positions et proposer les meilleurs coups."
  },
  zh: {
    lang_selector_label: "语言",
    nav_account: "账号",
    nav_support: "支持",
    nav_logout: "退出登录",
    nav_back_home: "返回首页",
    nav_back_login: "返回登录",
    login_title: "用户登录",
    login_hint: "登录后使用数据看板。",
    login_username: "用户名",
    login_password: "密码",
    login_button: "登录",
    login_guest: "游客登录",
    login_create_account: "创建账号",
    login_forgot_password: "忘记密码？",
    register_title: "创建账号",
    register_hint: "注册新账号以使用 Chess Data Stats。",
    register_username: "用户名",
    register_email: "邮箱",
    register_password: "密码（至少12位，含大小写/数字/符号）",
    register_button: "创建账号",
    forgot_title: "忘记密码",
    forgot_hint: "先申请重置邮件，再设置新密码。",
    forgot_username: "用户名",
    forgot_request_button: "发送重置邮件",
    forgot_token: "重置令牌",
    forgot_new_password: "新密码（至少12位，含大小写/数字/符号）",
    forgot_reset_button: "重置密码",
    account_title: "账号",
    account_hint: "设置或更新用于重置密码的邮箱。",
    account_email: "邮箱",
    account_save: "保存邮箱",
    support_title: "支持",
    support_hint: "请输入留言（最多200个字符），我们会通过邮件收到。",
    support_message_label: "留言",
    support_message_placeholder: "请输入你的留言...",
    support_send_button: "发送留言",
    support_guest_label: "未登录（访客）",
    home_title: "Chess Data Stats",
    home_hint: "添加用户名并选择日期范围（最多120天）。",
    home_platform: "平台",
    home_range: "范围（天）",
    home_default_mode: "默认模式",
    home_optional_exact_range: "可选：精确日期范围",
    home_from: "开始",
    home_to: "结束",
    home_date_override_hint: "如果两个日期都填写，将覆盖范围天数。",
    home_game_types: "对局类型",
    home_bullet: "超快棋",
    home_blitz: "快棋",
    home_rapid: "慢棋",
    home_add: "添加",
    home_upload_csv: "上传 CSV",
    home_csv_hint: "CSV：每行一个用户名，或逗号分隔。",
    home_generate: "生成统计页面",
    home_entry_fetch_title: "拉取对局数据",
    home_entry_fetch_desc: "拉取在线对局并生成统计表格。",
    home_entry_analysis_title: "对局分析",
    home_entry_analysis_desc: "粘贴或上传 PGN，并运行 Stockfish 分析。",
    home_banner_fetch_title: "拉取在线对局数据",
    home_banner_fetch_hint: "从 Chess.com 或 Lichess 拉取对局并生成统计。",
    home_banner_pgn_title: "上传 PGN + Stockfish 分析",
    home_banner_pgn_hint: "上传 PGN 文件并进行逐步引擎评分分析。",
    home_pgn_file_label: "PGN 文件",
    home_pgn_input_mode_label: "输入方式",
    home_pgn_input_mode_upload: "上传文件",
    home_pgn_input_mode_paste: "粘贴 PGN",
    home_pgn_paste_label: "粘贴 PGN",
    home_pgn_paste_placeholder: "在此粘贴 PGN 文本...",
    home_pgn_depth_label: "分析深度",
    home_pgn_upload_btn: "载入 PGN",
    home_pgn_analyze_btn: "运行 Stockfish 分析",
    home_pgn_download_btn: "下载 CSV",
    home_pgn_auto_load_hint: "PGN 会在上传文件或粘贴文本后自动载入。",
    home_pgn_ready_from_file: "PGN 文件已就绪（{chars} 字符）。",
    home_pgn_ready_from_paste: "粘贴的 PGN 已就绪（{chars} 字符）。",
    home_pgn_ready_from_both: "文件与粘贴 PGN 一致（{chars} 字符）。",
    home_pgn_conflict: "PGN 冲突：上传文件与粘贴文本不一致。请只保留一个来源或保持一致。",
    home_pgn_no_input: "请先上传 PGN 文件或粘贴 PGN 文本。",
    home_pgn_invalid_format: "PGN 格式无效，请重新填写后重试。",
    home_pgn_loaded: "PGN 已载入（{chars} 字符）。",
    home_pgn_load_failed: "PGN 载入失败：{error}",
    home_pgn_analyzing: "正在用 Stockfish 分析...",
    home_pgn_analysis_done: "分析完成：{count} 步，{failed} 步评估失败。",
    home_pgn_analyze_failed: "PGN 分析失败。",
    home_pgn_too_large: "PGN 内容过大。",
    home_pgn_rate_limited: "请求过多，请稍后重试。",
    pgn_eval_move_number: "步数",
    pgn_eval_side: "方",
    pgn_eval_move: "走法",
    pgn_eval_score: "评分",
    pgn_eval_bestmove: "最佳着法",
    pgn_eval_bestmove_eval: "最佳着法评分",
    pgn_eval_eval_gap: "评分差值",
    pgn_eval_accuracy: "精确度",
    pgn_eval_is_book_move: "库步",
    pgn_eval_opening_eco: "开局 ECO",
    pgn_eval_opening_name: "开局名称",
    pgn_eval_white_clock: "白方用时",
    pgn_eval_black_clock: "黑方用时",
    pgn_eval_wdl: "胜/和/负",
    pgn_analysis_title: "Stockfish PGN 分析",
    pgn_analysis_hint: "系统将逐步分析 PGN 并展示每步评分。",
    pgn_analysis_starting: "正在准备分析...",
    pgn_analysis_back_home: "返回首页",
    pgn_analysis_download_csv: "下载 CSV",
    pgn_analysis_progress_title: "正在分析 PGN",
    pgn_analysis_progress_running: "正在运行 Stockfish 分析...",
    pgn_analysis_slow_hint: "比预期更久，仍在分析中",
    pgn_analysis_progress_done: "分析完成。",
    pgn_analysis_progress_missing: "未找到 PGN 输入。",
    pgn_analysis_eta: "预计剩余时间：--",
    pgn_analysis_eta_seconds: "预计剩余时间：{seconds} 秒",
    pgn_analysis_eta_done: "已完成。",
    pgn_analysis_cancel: "取消",
    pgn_analysis_cancelled: "分析已取消。",
    pgn_analysis_close: "关闭",
    pgn_analysis_missing_input: "未找到 PGN 输入，请返回首页上传文件或粘贴 PGN。",
    stats_title: "对局统计",
    stats_loading: "加载数据中...",
    stats_username: "用户名",
    stats_games: "对局数",
    stats_breakdown: "分类",
    stats_win_rate: "胜率",
    stats_avg_duration: "平均时长",
    stats_rating_change: "等级分变化（范围）",
    stats_last_played: "最近对局",
    stats_download_csv: "下载 CSV",
    stats_download_raw: "下载原始数据",
    stats_view_raw: "查看原始数据",
    stats_raw_preview: "原始数据预览",
    stats_raw_preview_hint: "先查看原始对局数据，再决定是否下载。",
    stats_raw_platform: "平台",
    stats_raw_white_player: "白方",
    stats_raw_white_rating: "白方等级分",
    stats_raw_black_player: "黑方",
    stats_raw_black_rating: "黑方等级分",
    stats_raw_rating_gap: "双方等级分差（白-黑）",
    stats_raw_game_type: "对局类型",
    stats_raw_result: "结果",
    stats_raw_game_link: "对局链接",
    stats_raw_played_at: "对局时间 (UTC)",
    stats_raw_duration_ms: "时长毫秒",
    stats_raw_duration_min: "时长（分钟）",
    stats_raw_rating_diff: "等级分变化（用户变化）",
    stats_raw_rating: "等级分",
    raw_prev_page: "上一页",
    raw_next_page: "下一页",
    nav_back_stats: "返回对局统计",
    support_sending: "正在发送留言...",
    support_send_success: "留言已发送，感谢你的反馈。",
    support_send_failed: "发送失败，请重试。",
    support_message_required: "留言不能为空。",
    support_message_too_long: "留言最多 {max} 个字符。",
    support_email_service_not_configured: "支持邮件服务尚未配置。",
    faq_page_title: "常见问题 | Chess Data Stats",
    faq_heading: "常见问题",
    faq_hint: "关于数据拉取和 PGN 分析的常见问题。",
    faq_q1: "最多可以拉取多少天的对局数据？",
    faq_a1: "所选时间范围不能超过 120 天。",
    faq_q2: "PGN 可以同时文件上传和文本粘贴吗？",
    faq_a2: "可以。你可以上传 PGN 文件或粘贴 PGN 文本。若两者冲突，请只保留一个来源。",
    faq_q3: "分析结果可以导出为 CSV 吗？",
    faq_a3: "可以。对局统计和 PGN 分析结果都可以下载为 CSV。",
    faq_q4: "支持哪些平台？",
    faq_a4: "对局数据拉取支持 Chess.com 和 Lichess。",
    faq_q5: "PGN 分析里的 eval 分数和 best move 是怎么得到的？",
    faq_a5: "eval 分数来自“该步走完后”的引擎评估；best move 和 best move eval 来自“该步之前局面”的引擎推荐。",
    faq_q6: "Stockfish 是什么？",
    faq_a6: "Stockfish 是一个强大的开源国际象棋引擎，用于评估局面并给出最佳走法建议。"
  },
  es: {
    lang_selector_label: "Idioma",
    nav_account: "Cuenta",
    nav_support: "Soporte",
    nav_logout: "Cerrar sesión",
    nav_back_home: "Volver al inicio",
    nav_back_login: "Volver al inicio de sesión",
    login_title: "Inicio de sesión",
    login_hint: "Inicia sesión para usar el panel.",
    login_username: "Usuario",
    login_password: "Contraseña",
    login_button: "Entrar",
    login_guest: "Entrar como invitado",
    login_create_account: "Crear cuenta",
    login_forgot_password: "¿Olvidaste tu contraseña?",
    register_title: "Crear cuenta",
    register_hint: "Registra una cuenta para usar Chess Data Stats.",
    register_username: "Usuario",
    register_email: "Correo",
    register_password: "Contraseña (mín 12, may/min/número/símbolo)",
    register_button: "Crear cuenta",
    forgot_title: "Olvidé mi contraseña",
    forgot_hint: "Solicita un correo de restablecimiento y define una nueva contraseña.",
    forgot_username: "Usuario",
    forgot_request_button: "Solicitar correo",
    forgot_token: "Token de restablecimiento",
    forgot_new_password: "Nueva contraseña (mín 12, may/min/número/símbolo)",
    forgot_reset_button: "Restablecer contraseña",
    account_title: "Cuenta",
    account_hint: "Configura o actualiza tu correo para restablecer contraseña.",
    account_email: "Correo",
    account_save: "Guardar correo",
    support_title: "Soporte",
    support_hint: "Deja un mensaje (máx. 200 caracteres) y lo recibiremos por correo.",
    support_message_label: "Mensaje",
    support_message_placeholder: "Escribe tu mensaje...",
    support_send_button: "Enviar mensaje",
    support_guest_label: "Sin iniciar sesión (invitado)",
    home_title: "Chess Data Stats",
    home_hint: "Agrega usuarios y elige un rango de fechas (máx. 120 días).",
    home_platform: "Plataforma",
    home_range: "Rango (días)",
    home_default_mode: "Modo predeterminado",
    home_optional_exact_range: "Opcional: rango exacto",
    home_from: "Desde",
    home_to: "Hasta",
    home_date_override_hint: "Si completas ambas fechas, reemplazan el rango.",
    home_game_types: "Tipos de partida",
    home_bullet: "Bullet",
    home_blitz: "Blitz",
    home_rapid: "Rapid",
    home_add: "Agregar",
    home_upload_csv: "Subir CSV",
    home_csv_hint: "CSV: un usuario por línea o separado por comas.",
    home_generate: "Generar página de estadísticas",
    home_entry_fetch_title: "Obtener partidas",
    home_entry_fetch_desc: "Obtén partidas en línea y genera tablas de estadísticas.",
    home_entry_analysis_title: "Análisis de partida",
    home_entry_analysis_desc: "Pega o sube PGN y ejecuta análisis con Stockfish.",
    home_banner_fetch_title: "Obtener estadísticas en línea",
    home_banner_fetch_hint: "Trae partidas de Chess.com o Lichess y genera estadísticas.",
    home_banner_pgn_title: "Subir PGN + análisis Stockfish",
    home_banner_pgn_hint: "Sube un archivo PGN y ejecuta análisis jugada por jugada.",
    home_pgn_file_label: "Archivo PGN",
    home_pgn_input_mode_label: "Modo de entrada",
    home_pgn_input_mode_upload: "Subir archivo",
    home_pgn_input_mode_paste: "Pegar PGN",
    home_pgn_paste_label: "Pegar PGN",
    home_pgn_paste_placeholder: "Pega el texto PGN aquí...",
    home_pgn_depth_label: "Profundidad de análisis",
    home_pgn_upload_btn: "Cargar PGN",
    home_pgn_analyze_btn: "Ejecutar análisis Stockfish",
    home_pgn_download_btn: "Descargar CSV",
    home_pgn_auto_load_hint: "El PGN se carga automáticamente desde archivo o texto pegado.",
    home_pgn_ready_from_file: "Archivo PGN listo ({chars} caracteres).",
    home_pgn_ready_from_paste: "PGN pegado listo ({chars} caracteres).",
    home_pgn_ready_from_both: "El archivo y el texto pegado coinciden ({chars} caracteres).",
    home_pgn_conflict: "Conflicto de PGN: el archivo y el texto pegado son distintos. Usa solo una fuente o haz que coincidan.",
    home_pgn_no_input: "Primero sube un archivo PGN o pega texto PGN.",
    home_pgn_invalid_format: "Formato PGN no válido. Vuelve a ingresar el PGN e inténtalo de nuevo.",
    home_pgn_loaded: "PGN cargado ({chars} caracteres).",
    home_pgn_load_failed: "Error al cargar PGN: {error}",
    home_pgn_analyzing: "Analizando con Stockfish...",
    home_pgn_analysis_done: "Análisis completo: {count} jugadas, {failed} evaluaciones fallidas.",
    home_pgn_analyze_failed: "No se pudo analizar el PGN.",
    home_pgn_too_large: "El PGN es demasiado grande.",
    home_pgn_rate_limited: "Demasiadas solicitudes. Inténtalo pronto.",
    pgn_eval_move_number: "N.º",
    pgn_eval_side: "Lado",
    pgn_eval_move: "Jugada",
    pgn_eval_score: "Evaluación",
    pgn_eval_bestmove: "Mejor jugada",
    pgn_eval_bestmove_eval: "Eval mejor jugada",
    pgn_eval_eval_gap: "Diferencia eval",
    pgn_eval_accuracy: "Precisión",
    pgn_eval_is_book_move: "Jugada de libro",
    pgn_eval_opening_eco: "ECO apertura",
    pgn_eval_opening_name: "Nombre de apertura",
    pgn_eval_white_clock: "Tiempo blancas",
    pgn_eval_black_clock: "Tiempo negras",
    pgn_eval_wdl: "G/T/P",
    pgn_analysis_title: "Análisis PGN con Stockfish",
    pgn_analysis_hint: "Analizamos tu PGN jugada por jugada y mostramos la evaluación.",
    pgn_analysis_starting: "Preparando análisis...",
    pgn_analysis_back_home: "Volver al inicio",
    pgn_analysis_download_csv: "Descargar CSV",
    pgn_analysis_progress_title: "Analizando PGN",
    pgn_analysis_progress_running: "Ejecutando análisis Stockfish...",
    pgn_analysis_slow_hint: "tarda más de lo esperado, sigue en curso",
    pgn_analysis_progress_done: "Análisis completado.",
    pgn_analysis_progress_missing: "No se encontró entrada PGN.",
    pgn_analysis_eta: "Tiempo estimado restante: --",
    pgn_analysis_eta_seconds: "Tiempo estimado restante: {seconds}s",
    pgn_analysis_eta_done: "Completado.",
    pgn_analysis_cancel: "Cancelar",
    pgn_analysis_cancelled: "Análisis cancelado.",
    pgn_analysis_close: "Cerrar",
    pgn_analysis_missing_input: "No se encontró entrada PGN. Vuelve atrás y sube o pega un PGN.",
    stats_title: "Estadísticas",
    stats_loading: "Cargando datos...",
    stats_username: "Usuario",
    stats_games: "Partidas",
    stats_breakdown: "Desglose",
    stats_win_rate: "Tasa de victoria",
    stats_avg_duration: "Duración media",
    stats_rating_change: "Cambio de rating (rango)",
    stats_last_played: "Última partida",
    stats_download_csv: "Descargar CSV",
    stats_download_raw: "Descargar datos crudos",
    stats_view_raw: "Ver datos crudos",
    stats_raw_preview: "Vista previa de datos crudos",
    stats_raw_preview_hint: "Primero revisa las partidas crudas y luego decide si descargar.",
    stats_raw_platform: "Plataforma",
    stats_raw_white_player: "Jugador blancas",
    stats_raw_white_rating: "Elo blancas",
    stats_raw_black_player: "Jugador negras",
    stats_raw_black_rating: "Elo negras",
    stats_raw_rating_gap: "Diferencia de Elo (Blancas-Negras)",
    stats_raw_game_type: "Tipo de partida",
    stats_raw_result: "Resultado",
    stats_raw_game_link: "Enlace de partida",
    stats_raw_played_at: "Jugado en (UTC)",
    stats_raw_duration_ms: "Duración ms",
    stats_raw_duration_min: "Duración (min)",
    stats_raw_rating_diff: "Cambio de rating (usuario)",
    stats_raw_rating: "Rating",
    raw_prev_page: "Anterior",
    raw_next_page: "Siguiente",
    nav_back_stats: "Volver a estadísticas",
    support_sending: "Enviando mensaje...",
    support_send_success: "Mensaje enviado. Gracias por tu comentario.",
    support_send_failed: "No se pudo enviar el mensaje. Inténtalo de nuevo.",
    support_message_required: "El mensaje es obligatorio.",
    support_message_too_long: "El mensaje debe tener como máximo {max} caracteres.",
    support_email_service_not_configured: "El servicio de correo de soporte aún no está configurado.",
    faq_page_title: "Preguntas frecuentes | Chess Data Stats",
    faq_heading: "Preguntas frecuentes",
    faq_hint: "Preguntas comunes sobre obtención de datos y análisis PGN.",
    faq_q1: "¿Cuántos días de partidas puedo consultar?",
    faq_a1: "El rango seleccionado no puede superar 120 días.",
    faq_q2: "¿Puedo subir PGN por archivo y por texto pegado?",
    faq_a2: "Sí. Puedes subir un archivo PGN o pegar texto PGN. Si hay conflicto, conserva una sola fuente.",
    faq_q3: "¿Puedo exportar los resultados de análisis en CSV?",
    faq_a3: "Sí. Tanto las estadísticas como los resultados de análisis PGN se pueden descargar en CSV.",
    faq_q4: "¿Qué plataformas son compatibles?",
    faq_a4: "La obtención de partidas es compatible con Chess.com y Lichess.",
    faq_q5: "¿Cómo se obtienen eval score y best move en el análisis PGN?",
    faq_a5: "El eval score proviene de la evaluación del motor después de la jugada realizada. Best move y best move eval vienen de la recomendación del motor antes de esa jugada.",
    faq_q6: "¿Qué es Stockfish?",
    faq_a6: "Stockfish es un potente motor de ajedrez de código abierto usado para evaluar posiciones y sugerir mejores jugadas."
  },
  sv: {
    lang_selector_label: "Språk",
    nav_account: "Konto",
    nav_support: "Support",
    nav_logout: "Logga ut",
    nav_back_home: "Tillbaka till startsidan",
    nav_back_login: "Tillbaka till inloggning",
    login_title: "Användarinloggning",
    login_hint: "Logga in för att använda analyspanelen.",
    login_username: "Användarnamn",
    login_password: "Lösenord",
    login_button: "Logga in",
    login_guest: "Logga in som gäst",
    login_create_account: "Skapa konto",
    login_forgot_password: "Glömt lösenord?",
    register_title: "Skapa konto",
    register_hint: "Registrera ett konto för att använda Chess Data Stats.",
    register_username: "Användarnamn",
    register_email: "E-post",
    register_password: "Lösenord (min 12, versaler/gemener/siffra/symbol)",
    register_button: "Skapa konto",
    forgot_title: "Glömt lösenord",
    forgot_hint: "Begär ett återställningsmail och ange nytt lösenord.",
    forgot_username: "Användarnamn",
    forgot_request_button: "Begär återställningsmail",
    forgot_token: "Återställningstoken",
    forgot_new_password: "Nytt lösenord (min 12, versaler/gemener/siffra/symbol)",
    forgot_reset_button: "Återställ lösenord",
    account_title: "Konto",
    account_hint: "Ange eller uppdatera din e-post för lösenordsåterställning.",
    account_email: "E-post",
    account_save: "Spara e-post",
    support_title: "Support",
    support_hint: "Lämna ett meddelande (max 200 tecken) så får vi det via e-post.",
    support_message_label: "Meddelande",
    support_message_placeholder: "Skriv ditt meddelande...",
    support_send_button: "Skicka meddelande",
    support_guest_label: "Inte inloggad (gäst)",
    home_title: "Chess Data Stats",
    home_hint: "Lägg till användare och välj datumintervall (max 120 dagar).",
    home_platform: "Plattform",
    home_range: "Intervall (dagar)",
    home_default_mode: "Standardläge",
    home_optional_exact_range: "Valfritt: exakt datumintervall",
    home_from: "Från",
    home_to: "Till",
    home_date_override_hint: "Om båda datumen anges ersätter de intervallet.",
    home_game_types: "Partityper",
    home_bullet: "Bullet",
    home_blitz: "Blitz",
    home_rapid: "Rapid",
    home_add: "Lägg till",
    home_upload_csv: "Ladda upp CSV",
    home_csv_hint: "CSV: ett användarnamn per rad eller kommaseparerat.",
    home_generate: "Skapa statistiksida",
    home_entry_fetch_title: "Hämta partidata",
    home_entry_fetch_desc: "Hämta partier online och bygg statistiktabeller.",
    home_entry_analysis_title: "Partianalys",
    home_entry_analysis_desc: "Klistra in eller ladda upp PGN och kör Stockfish-analys.",
    home_banner_fetch_title: "Hämta statistik online",
    home_banner_fetch_hint: "Hämta partier från Chess.com eller Lichess och skapa statistik.",
    home_banner_pgn_title: "Ladda upp PGN + Stockfish-analys",
    home_banner_pgn_hint: "Ladda upp en PGN-fil och kör drag-för-drag analys.",
    home_pgn_file_label: "PGN-fil",
    home_pgn_input_mode_label: "Inmatningsläge",
    home_pgn_input_mode_upload: "Ladda upp fil",
    home_pgn_input_mode_paste: "Klistra in PGN",
    home_pgn_paste_label: "Klistra in PGN",
    home_pgn_paste_placeholder: "Klistra in PGN-text här...",
    home_pgn_depth_label: "Analysdjup",
    home_pgn_upload_btn: "Ladda PGN",
    home_pgn_analyze_btn: "Kör Stockfish-analys",
    home_pgn_download_btn: "Ladda ner CSV",
    home_pgn_auto_load_hint: "PGN laddas automatiskt från fil eller inklistrad text.",
    home_pgn_ready_from_file: "PGN-fil klar ({chars} tecken).",
    home_pgn_ready_from_paste: "Inklistrad PGN klar ({chars} tecken).",
    home_pgn_ready_from_both: "Fil och inklistrad PGN matchar ({chars} tecken).",
    home_pgn_conflict: "PGN-konflikt: uppladdad fil och inklistrad text skiljer sig. Behåll en källa eller gör dem lika.",
    home_pgn_no_input: "Ladda först upp en PGN-fil eller klistra in PGN-text.",
    home_pgn_invalid_format: "Ogiltigt PGN-format. Fyll i PGN igen och försök på nytt.",
    home_pgn_loaded: "PGN laddad ({chars} tecken).",
    home_pgn_load_failed: "Misslyckades att läsa PGN: {error}",
    home_pgn_analyzing: "Analyserar med Stockfish...",
    home_pgn_analysis_done: "Analys klar: {count} drag, {failed} misslyckade utvärderingar.",
    home_pgn_analyze_failed: "Kunde inte analysera PGN.",
    home_pgn_too_large: "PGN är för stor.",
    home_pgn_rate_limited: "För många förfrågningar. Försök snart igen.",
    pgn_eval_move_number: "Drag #",
    pgn_eval_side: "Sida",
    pgn_eval_move: "Drag",
    pgn_eval_score: "Utvärdering",
    pgn_eval_bestmove: "Bästa drag",
    pgn_eval_bestmove_eval: "Eval bästa drag",
    pgn_eval_eval_gap: "Evalskillnad",
    pgn_eval_accuracy: "Precision",
    pgn_eval_is_book_move: "Bokdrag",
    pgn_eval_opening_eco: "ECO-öppning",
    pgn_eval_opening_name: "Öppningsnamn",
    pgn_eval_white_clock: "Vit klocka",
    pgn_eval_black_clock: "Svart klocka",
    pgn_eval_wdl: "V/R/F",
    pgn_analysis_title: "Stockfish PGN-analys",
    pgn_analysis_hint: "Vi analyserar din PGN drag för drag och visar utvärdering.",
    pgn_analysis_starting: "Förbereder analys...",
    pgn_analysis_back_home: "Tillbaka till startsidan",
    pgn_analysis_download_csv: "Ladda ner CSV",
    pgn_analysis_progress_title: "Analyserar PGN",
    pgn_analysis_progress_running: "Kör Stockfish-analys...",
    pgn_analysis_slow_hint: "tar längre tid än väntat, kör fortfarande",
    pgn_analysis_progress_done: "Analys klar.",
    pgn_analysis_progress_missing: "Ingen PGN-indata hittades.",
    pgn_analysis_eta: "Beräknad återstående tid: --",
    pgn_analysis_eta_seconds: "Beräknad återstående tid: {seconds}s",
    pgn_analysis_eta_done: "Klart.",
    pgn_analysis_cancel: "Avbryt",
    pgn_analysis_cancelled: "Analysen avbröts.",
    pgn_analysis_close: "Stäng",
    pgn_analysis_missing_input: "Ingen PGN-indata hittades. Gå tillbaka och ladda upp eller klistra in PGN.",
    stats_title: "Spelstatistik",
    stats_loading: "Laddar data...",
    stats_username: "Användarnamn",
    stats_games: "Partier",
    stats_breakdown: "Uppdelning",
    stats_win_rate: "Vinstprocent",
    stats_avg_duration: "Genomsnittlig speltid",
    stats_rating_change: "Ratingändring (intervall)",
    stats_last_played: "Senast spelad",
    stats_download_csv: "Ladda ner CSV",
    stats_download_raw: "Ladda ner rådata",
    stats_view_raw: "Visa rådata",
    stats_raw_preview: "Förhandsgranskning av rådata",
    stats_raw_preview_hint: "Visa först råpartier och välj sedan om du vill ladda ner.",
    stats_raw_platform: "Plattform",
    stats_raw_white_player: "Vit spelare",
    stats_raw_white_rating: "Vit rating",
    stats_raw_black_player: "Svart spelare",
    stats_raw_black_rating: "Svart rating",
    stats_raw_rating_gap: "Rating-skillnad (Vit-Svart)",
    stats_raw_game_type: "Partityp",
    stats_raw_result: "Resultat",
    stats_raw_game_link: "Partilänk",
    stats_raw_played_at: "Spelad vid (UTC)",
    stats_raw_duration_ms: "Varaktighet ms",
    stats_raw_duration_min: "Varaktighet (min)",
    stats_raw_rating_diff: "Ratingförändring (användare)",
    stats_raw_rating: "Rating",
    raw_prev_page: "Föregående",
    raw_next_page: "Nästa",
    nav_back_stats: "Tillbaka till statistik",
    support_sending: "Skickar meddelande...",
    support_send_success: "Meddelandet skickades. Tack för din feedback.",
    support_send_failed: "Kunde inte skicka meddelandet. Försök igen.",
    support_message_required: "Meddelande krävs.",
    support_message_too_long: "Meddelandet får vara högst {max} tecken.",
    support_email_service_not_configured: "Supportens e-posttjänst är inte konfigurerad än.",
    faq_page_title: "FAQ | Chess Data Stats",
    faq_heading: "FAQ",
    faq_hint: "Vanliga frågor om datainsamling och PGN-analys.",
    faq_q1: "Hur många dagar med partier kan jag hämta?",
    faq_a1: "Det valda intervallet får inte överstiga 120 dagar.",
    faq_q2: "Kan jag ladda upp PGN både som fil och inklistrad text?",
    faq_a2: "Ja. Du kan ladda upp en PGN-fil eller klistra in PGN-text. Vid konflikt, behåll endast en källa.",
    faq_q3: "Kan jag exportera analysresultat till CSV?",
    faq_a3: "Ja. Både spelstatistik och PGN-analysresultat kan laddas ner som CSV.",
    faq_q4: "Vilka plattformar stöds?",
    faq_a4: "Hämtning av partidata stöder Chess.com och Lichess.",
    faq_q5: "Hur tas eval-score och best move fram i PGN-analysen?",
    faq_a5: "Eval-score kommer från motorns utvärdering efter det spelade draget. Best move och best move eval kommer från motorns rekommendation före det draget.",
    faq_q6: "Vad är Stockfish?",
    faq_a6: "Stockfish är en stark öppen källkod-schackmotor som används för att utvärdera ställningar och föreslå bästa drag."
  }
};

function getStoredLanguage() {
  const lang = localStorage.getItem(LANG_STORAGE_KEY);
  return SUPPORTED_LANGS.includes(lang) ? lang : "en";
}

function translateKey(lang, key) {
  const langPack = TRANSLATIONS[lang] || TRANSLATIONS.en;
  return langPack[key] || TRANSLATIONS.en[key] || key;
}

function formatTemplate(value, params) {
  if (!params) {
    return value;
  }
  return value.replace(/\{([a-zA-Z0-9_]+)\}/g, (_all, key) => {
    return Object.prototype.hasOwnProperty.call(params, key) ? String(params[key]) : "";
  });
}

function applyTranslations(lang) {
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    const key = el.getAttribute("data-i18n");
    if (!key) return;
    el.textContent = translateKey(lang, key);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    const key = el.getAttribute("data-i18n-placeholder");
    if (!key) return;
    el.setAttribute("placeholder", translateKey(lang, key));
  });
  document.querySelectorAll("[data-i18n-title]").forEach((el) => {
    const key = el.getAttribute("data-i18n-title");
    if (!key) return;
    el.textContent = translateKey(lang, key);
  });
}

function injectLanguageSelector(lang) {
  const wrap = document.createElement("div");
  wrap.className = "lang-corner";

  const label = document.createElement("label");
  label.setAttribute("for", "lang-select");
  label.className = "lang-corner-label";
  label.textContent = translateKey(lang, "lang_selector_label");

  const select = document.createElement("select");
  select.id = "lang-select";
  select.className = "lang-corner-select";

  SUPPORTED_LANGS.forEach((value) => {
    const option = document.createElement("option");
    option.value = value;
    option.textContent = LANG_LABELS[value];
    if (value === lang) {
      option.selected = true;
    }
    select.appendChild(option);
  });

  select.addEventListener("change", () => {
    const next = select.value;
    localStorage.setItem(LANG_STORAGE_KEY, next);
    applyTranslations(next);
    label.textContent = translateKey(next, "lang_selector_label");
    window.dispatchEvent(new CustomEvent("languagechange", { detail: { lang: next } }));
  });

  wrap.appendChild(label);
  wrap.appendChild(select);
  document.body.appendChild(wrap);
}

const currentLanguage = getStoredLanguage();
applyTranslations(currentLanguage);
injectLanguageSelector(currentLanguage);

function trackButtonClicks() {
  if (window.__buttonClickTrackerAttached) return;
  window.__buttonClickTrackerAttached = true;

  const isTrackableButton = (el) => {
    if (!el) return false;
    if (el.tagName === "BUTTON") return true;
    if (el.tagName === "INPUT") {
      const type = (el.getAttribute("type") || "").toLowerCase();
      return type === "button" || type === "submit";
    }
    if (el.tagName === "A" && el.classList.contains("button-link")) return true;
    return false;
  };

  document.addEventListener("click", (event) => {
    const target = event.target instanceof Element ? event.target : null;
    if (!target) return;
    const button = target.closest("button, input[type='button'], input[type='submit'], a.button-link");
    if (!button || !isTrackableButton(button)) return;
    if (button.getAttribute("data-track") === "false") return;
    const canTrackAnalytics =
      window.cookieConsent &&
      typeof window.cookieConsent.canUse === "function" &&
      window.cookieConsent.canUse("analytics");
    if (!canTrackAnalytics) return;

    const buttonId =
      button.getAttribute("data-track-id") ||
      button.id ||
      button.getAttribute("data-i18n") ||
      button.getAttribute("name") ||
      button.getAttribute("aria-label") ||
      "";
    const buttonLabel = (button.textContent || button.getAttribute("value") || "").trim().slice(0, 200);
    const pagePath = window.location.pathname || "/";

    fetch("/api/metrics/button-click", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      keepalive: true,
      body: JSON.stringify({
        page_path: pagePath,
        button_id: buttonId,
        button_label: buttonLabel
      })
    }).catch(() => {});
  });
}

trackButtonClicks();

window.i18n = {
  getLanguage: getStoredLanguage,
  t(key, params) {
    const lang = getStoredLanguage();
    return formatTemplate(translateKey(lang, key), params);
  }
};
